const SHOW_SEARCH_BARS = 'SHOW_SEARCH_BARS'
const HIDDEN_SEARCH_BARS = 'HIDDEN_SEARCH_BARS'
const AUTHORIZATION_SUCCESS = 'AUTHORIZATION_SUCCESS'
const AUTHORIZATION_EXIT = 'AUTHORIZATION_EXIT'
const GET_ITEMSOURCE_SUCCESS = 'GET_ITEMSOURCE_SUCCESS'
const CLEAN_ITEMSOURCE = 'CLEAN_ITEMSOURCE'
const LOADING_ITEMSOURCE = 'LOADING_ITEMSOURCE'
const NONE_ITEMSOURCE = 'NONE_ITEMSOURCE'
const GET_PROCESSES_DETAILS = 'GET_PROCESSES_DETAILS'
const UNDOBYME = 'UNDOBYME'
const SHOW_CHOICE = 'SHOW_CHOICE'
const HIDDEN_CHOICE = 'HIDDEN_CHOICE'
const SHOW_CHOICE_BARS = 'SHOW_CHOICE_BARS'
const HIDDEN_CHOICE_BARS = 'HIDDEN_CHOICE_BARS'
const GET_CHOICESOURCE_SUCCESS = 'GET_CHOICESOURCE_SUCCESS'
const CLEAN_CHOICESOURCE = 'CLEAN_CHOICESOURCE'
const SET_CHOICE_CONDITION = 'SET_CHOICE_CONDITION'
const INIT_CHOICE_CONDITION = 'INIT_CHOICE_CONDITION'
const SET_SEARCH_SOURCE = 'SET_SEARCH_SOURCE'
const INIT_SEARCH_SOURCE = 'INIT_SEARCH_SOURCE'
const SET_SEARCH_CONDITION = 'SET_SEARCH_CONDITION'
const CLEAN_SEARCH_CONDITION = 'CLEAN_SEARCH_CONDITION'
const ACCEPT_REJECT_SUCCESS = 'ACCEPT_REJECT_SUCCESS'
const INIT_OPERATE_STATUS = 'INIT_OPERATE_STATUS'
const CLEAN_PROCESSES_DETAILS = 'CLEAN_PROCESSES_DETAILS'
const SET_CURRENT_CHOICESOURCE = 'SET_CURRENT_CHOICESOURCE'
const INIT_CHOICESOURCE = 'INIT_CHOICESOURCE'

export {
  SHOW_SEARCH_BARS,
  HIDDEN_SEARCH_BARS,
  AUTHORIZATION_SUCCESS,
  AUTHORIZATION_EXIT,
  GET_ITEMSOURCE_SUCCESS,
  CLEAN_ITEMSOURCE,
  LOADING_ITEMSOURCE,
  NONE_ITEMSOURCE,
  GET_PROCESSES_DETAILS,
  CLEAN_PROCESSES_DETAILS,
  UNDOBYME,
  SHOW_CHOICE,
  HIDDEN_CHOICE,
  SHOW_CHOICE_BARS,
  HIDDEN_CHOICE_BARS,
  GET_CHOICESOURCE_SUCCESS,
  CLEAN_CHOICESOURCE,
  SET_CHOICE_CONDITION,
  INIT_CHOICE_CONDITION,
  SET_CURRENT_CHOICESOURCE,
  INIT_CHOICESOURCE,
  SET_SEARCH_SOURCE,
  INIT_SEARCH_SOURCE,
  SET_SEARCH_CONDITION,
  CLEAN_SEARCH_CONDITION,
  ACCEPT_REJECT_SUCCESS,
  INIT_OPERATE_STATUS
}
