const ERROR_MSG = 'ERROR_MSG'
const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
const LOAD_DATA = 'LOAD_DATA'

export {
  ERROR_MSG,
  REGISTER_SUCCESS,
  LOGIN_SUCCESS,
  LOAD_DATA
}
